env: pro
server:
  port: 40001
spring:
  # 选择日志输出级别
  profiles.active: pro
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kunkka?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是20
      maximum-pool-size: 20
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: dbPool
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

jwt:
  subject: kunkka
  # 认证过期时间 0.5h
  expiration: 1800000
  secret: dJF&*JOFJO#Jdiojocijiosj23e2d9i0fjsdj
  auth.id: kunkkaId
  authentication.urls: '^.*/api/open.*$'

salt:
  password: IDJIFJio329&*&*ejenfi323hdhhdh

limit.max: 5

csrf.whitelist.urls: '^http://acgv.fun.*$|^https://acgv.fun.*$'
# 测试
#csrf.whitelist.urls: '^$'

authentication.whitelist.urls: '^.*/api/user/login.*$|^.*/api/public/.*$|^.*/api/user/register.*$|^.*/api/open.*$'

redis:
  host: localhost
  port: 6379
  password: djnfiojwsoedrfjoi3948209JFIEJHIOrjewoirjw

